name: googler
version: 'master'
version-script: git -C parts/googler/build describe --tags | sed 's/v//'
summary: power tool to Google (Web & News) and Google Site Search from the command-line
description: |
  googler is a power tool to Google (Web & News) and Google Site
  Search from the command-line. It shows the title, URL and abstract
  for each result, which can be directly opened in a browser from the
  terminal. Results are fetched in pages (with page navigation).
  Supports sequential searches in a single googler instance.
  googler isn't affiliated to Google in any way.

grade: stable
confinement: strict

apps:
  googler:
    command: usr/local/bin/googler
    plugs: [network]
    environment:
      PYTHONIOENCODING: utf-8

parts:
  googler:
    plugin: make
    source: https://github.com/jarun/googler.git
    override-build: |
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_committed_tag_ver="$(echo ${last_committed_tag} | sed 's/v//')"
      last_released_tag="$(snap info googler | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag_ver}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi
      make disable-self-upgrade
      snapcraftctl build
    stage-packages:
      - python3
